# Generated by Django 6.0 on 2026-01-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "salary",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("US", "United States"),
                            ("CA", "Canada"),
                            ("GB", "United Kingdom"),
                            ("AR", "Argentina"),
                        ],
                        default="US",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed"), ("PAUSED", "Paused")],
                        default="OPEN",
                    ),
                ),
            ],
        ),
    ]
