# Generated by Django 6.0 on 2026-02-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
